-- MySQL Script generated by MySQL Workbench
-- Wed Sep  2 14:13:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema purchase_management_dashboard
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `purchase_management_dashboard` ;

-- -----------------------------------------------------
-- Schema purchase_management_dashboard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `purchase_management_dashboard` DEFAULT CHARACTER SET utf8mb4 ;
USE `purchase_management_dashboard` ;

-- -----------------------------------------------------
-- Table `purchase_management_dashboard`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `purchase_management_dashboard`.`users` ;

CREATE TABLE IF NOT EXISTS `purchase_management_dashboard`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(100) NOT NULL,
  `pwd` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purchase_management_dashboard`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `purchase_management_dashboard`.`products` ;

CREATE TABLE IF NOT EXISTS `purchase_management_dashboard`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `reference` INT(50) NOT NULL,
  `category` ENUM('Electromenager', 'TV-HIFI', 'Bricolage') NOT NULL,
  `price` FLOAT NOT NULL,
  `purchase_date` DATETIME NOT NULL,
  `warranty_date` DATETIME NOT NULL,
  `purchase_place` ENUM('Direct', 'Online') NOT NULL,
  `place_adress` TEXT(150) NOT NULL,
  `product_maintenance` LONGTEXT NOT NULL,
  `purchase_receipt` VARCHAR(150) NOT NULL,
  `user_manual` LONGTEXT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_products_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `purchase_management_dashboard`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_products_users_idx` ON `purchase_management_dashboard`.`products` (`users_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
